# Copyright 2026 The EASYDEL Author @erfanzar (Erfan Zare Chavoshi).
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Step3.5 tool parser module.

This module provides the Step3p5ToolParser class for parsing XML-style tool
calls generated by Step 3.5 models. The format is identical to Qwen3 Coder:

    <tool_call>
    <function=name>
    <parameter=param1>value1</parameter>
    <parameter=param2>value2</parameter>
    </function>
    </tool_call>
"""

from __future__ import annotations

from ..abstract_tool import ToolParserManager
from .qwen3coder_tool_parser import Qwen3CoderToolParser


@ToolParserManager.register_module(["step3p5", "step3.5"])  # pyright: ignore[reportUntypedClassDecorator]
class Step3p5ToolParser(Qwen3CoderToolParser):
    """Tool parser for Step 3.5 models.

    Uses the same XML-based tool calling format as Qwen3 Coder:
        <tool_call>
        <function=name>
        <parameter=param1>value1</parameter>
        </function>
        </tool_call>

    See Also:
        Qwen3CoderToolParser: The parent class providing all implementation.
    """

    pass
