# Copyright 2026 The EASYDEL Author @erfanzar (Erfan Zare Chavoshi).
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     https://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Reasoning parsers for MiniMax M2 chain-of-thought models.

MiniMax M2 uses the ``<think>``/``</think>`` grammar but has two operating
modes depending on configuration:

* :class:`MiniMaxM2ReasoningParser` — asymmetric mode: the model never emits
  the opening ``<think>`` marker, only the closing ``</think>``. Everything
  before ``</think>`` is treated as reasoning. Any stray ``<think>``
  literals are stripped before reasoning is surfaced.
* :class:`MiniMaxM2AppendThinkReasoningParser` — symmetric-compatible mode
  for configurations that drop the start tag: synthetically prepends
  ``<think>`` to the output before delegating to the standard
  :class:`BaseThinkingReasoningParser` machinery.
"""

from __future__ import annotations

from collections.abc import Sequence

from ...openai_api_modules import DeltaMessage
from ..abstract_reasoning import ReasoningParserManager
from ..basic_parsers import BaseThinkingReasoningParser


@ReasoningParserManager.register_module(["minimax_m2"])  # pyright: ignore[reportUntypedClassDecorator]
class MiniMaxM2ReasoningParser(BaseThinkingReasoningParser):
    """Asymmetric MiniMax M2 reasoning parser keyed off ``</think>`` only.

    The model never emits ``<think>``; the parser therefore treats every
    text chunk before the first ``</think>`` as reasoning and everything
    after as visible content. The ``start_token`` attribute is retained
    purely so that stray literal occurrences can be stripped from the
    surfaced reasoning text.

    Attributes:
        start_token: Reasoning open tag ``"<think>"`` — kept only to
            recognise/strip stray occurrences; the model normally does
            not emit it.
        end_token: Reasoning close tag ``"</think>"`` — the boundary that
            flips streaming output from ``reasoning_content`` to
            ``content``.
    """

    start_token = "<think>"  # Not generated by model, but used for logic
    end_token = "</think>"

    def extract_reasoning(self, model_output: str, request=None) -> tuple[str | None, str | None]:
        """Split the output at ``</think>``.

        Args:
            model_output: Full decoded text produced by the model.
            request: Optional inference request; unused, kept for interface
                parity with sibling parsers.

        Returns:
            Tuple ``(reasoning, content)`` where ``reasoning`` is the text
            before the first ``</think>`` (with any stray ``<think>``
            literals removed) and ``content`` is the text after it. When
            ``</think>`` is absent: if ``<think>`` appears the text is
            treated as an unfinished reasoning block
            (``(reasoning, None)``); otherwise the whole output is
            visible content (``(None, model_output)``).
        """
        if self.end_token not in model_output:
            if self.start_token in model_output:
                cleaned = model_output.replace(self.start_token, "").strip()
                return cleaned or None, None
            return None, model_output
        # Everything before end token is reasoning (even without start token)
        parts = model_output.split(self.end_token, 1)
        reasoning = parts[0].replace(self.start_token, "").strip()
        content = parts[1].strip() if len(parts) > 1 else None
        return reasoning or None, content

    def extract_reasoning_streaming(
        self,
        previous_text: str,
        current_text: str,
        delta_text: str,
        previous_token_ids: Sequence[int],
        current_token_ids: Sequence[int],
        delta_token_ids: Sequence[int],
        request=None,
    ) -> DeltaMessage | None:
        """Stream reasoning until ``</think>`` and visible content thereafter.

        Args:
            previous_text: Cumulative text before this chunk; checked for
                ``</think>`` to decide whether reasoning has already ended.
            current_text: Cumulative text including this chunk (unused).
            delta_text: Newly produced text in this chunk.
            previous_token_ids: Token IDs before this chunk (unused).
            current_token_ids: Token IDs including this chunk (unused).
            delta_token_ids: Token IDs for ``delta_text`` (unused).
            request: Optional inference request (unused).

        Returns:
            A :class:`DeltaMessage` carrying ``reasoning_content`` while
            still inside the block, both halves when ``</think>`` straddles
            the chunk, or ``content`` only once reasoning has ended;
            ``None`` when ``delta_text`` is empty or only contained a
            stripped ``<think>`` literal.
        """
        if not delta_text:
            return None

        has_end_in_prev = self.end_token in previous_text
        has_end_in_delta = self.end_token in delta_text

        if has_end_in_prev:
            return DeltaMessage(content=delta_text)

        if has_end_in_delta:
            parts = delta_text.split(self.end_token, 1)
            reasoning_part = parts[0].replace(self.start_token, "")
            content_part = parts[1] if len(parts) > 1 else None
            return DeltaMessage(
                reasoning_content=reasoning_part if reasoning_part else None,
                content=content_part if content_part else None,
            )

        # Still accumulating reasoning (no end token yet)
        cleaned = delta_text.replace(self.start_token, "")
        return DeltaMessage(reasoning_content=cleaned) if cleaned else None


@ReasoningParserManager.register_module(["minimax_m2_append_think"])  # pyright: ignore[reportUntypedClassDecorator]
class MiniMaxM2AppendThinkReasoningParser(BaseThinkingReasoningParser):
    """MiniMax M2 reasoning parser that synthesises a missing ``<think>`` tag.

    Some MiniMax M2 configurations strip the opening reasoning marker even
    though downstream parsing still expects the symmetric grammar. This
    subclass restores the marker at the front of the output (when missing)
    before forwarding to the standard
    :class:`BaseThinkingReasoningParser` machinery for the actual
    extraction. The streaming path is *not* overridden — it falls through
    to the base class.

    Attributes:
        start_token: Reasoning open tag ``"<think>"``; injected at the
            front of the output when missing.
        end_token: Reasoning close tag ``"</think>"`` matched verbatim.
    """

    start_token = "<think>"
    end_token = "</think>"

    def extract_reasoning(self, model_output: str, request=None) -> tuple[str | None, str | None]:
        """Inject ``<think>`` if absent and delegate to the base parser.

        Args:
            model_output: Full decoded text produced by the model.
            request: Optional inference request forwarded to the base
                class.

        Returns:
            Tuple ``(reasoning, content)`` produced by the base
            ``<think>``/``</think>`` parser after the prefix has been
            normalised.
        """
        if self.start_token not in model_output:
            model_output = self.start_token + model_output
        return super().extract_reasoning(model_output, request)
