# Copyright 2026 The EasyDeL/ejKernel Author @erfanzar (Erfan Zare Chavoshi).
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Utility functions and tuned block sizes for Ragged Paged Attention V3.

This module provides utility functions for TPU device detection, block size
selection, memory alignment, and performance tuning for the ragged paged
attention V3 kernel. It includes extensive pre-tuned block size configurations
for different TPU generations, workload characteristics, and head dimensions.

Key Components:
    - cdiv: Ceiling division utility for block calculations
    - align_to: Memory alignment helper for TPU tile requirements
    - get_dtype_bitwidth/get_dtype_packing: Data type packing calculations
    - next_power_of_2: Power-of-2 alignment for block sizes
    - get_device_name: TPU device identification with variant support
    - get_tpu_version: Numeric TPU version extraction
    - get_tuned_block_sizes: Block size lookup for head_dim >= 128
    - get_tuned_block_sizes_h64: Specialized block sizes for head_dim=64

Block Size Parameters:
    - bkv (num_kv_pages_per_block): Number of KV cache pages processed per
      Flash Attention block. Larger values improve HBM bandwidth utilization
    - bq (num_queries_per_block): Number of query tokens processed per block

Tuning Structure:
    Tuned values live in the shipped tuned-kernel table
    (``ejkernel/ops/tuned/tuned_kernels.db``) under the kernel name
    ``ragged_page_attention_v3``, keyed by device, dtype signature and a
    bucketed shape (page_size, q_heads, kv_heads, head_dim, max_len) ->
    ``{num_kv_pages_per_block, num_queries_per_block}``.

    They were a ~4200-line nested dict in this module until Aug 2026. Same
    values, but indexed rather than parsed at import, sharing one schema with
    every other kernel, and regenerated by sweeps instead of hand-edited.
    Read them with :func:`lookup_tuned_block_sizes`; key derivation is
    unchanged (:func:`get_lookup_keys`).

TPU Device Support:
    - TPU v5e/v5 lite: Entry-level TPU configurations
    - TPU v5p: High-performance TPU variant
    - TPU v6e: Latest generation optimizations
    - TPU v7/7x: Future-ready configurations

Head Dimension Variants:
    - head_dim=64: Use get_tuned_block_sizes_h64() for K/V concatenated layout
    - head_dim>=128: Use get_tuned_block_sizes() for standard layout

Example:
    >>> # Get block sizes for standard attention
    >>> bkv, bq = get_tuned_block_sizes(
    ...     q_dtype=jnp.bfloat16,
    ...     kv_dtype=jnp.bfloat16,
    ...     num_q_heads=32,
    ...     num_kv_heads=8,
    ...     head_dim=128,
    ...     page_size=64,
    ...     max_num_tokens=2048,
    ...     pages_per_seq=256,
    ... )

    >>> # Get block sizes for head_dim=64 variant
    >>> bkv_h64, bq_h64 = get_tuned_block_sizes_h64(
    ...     q_dtype=jnp.bfloat16,
    ...     kv_dtype=jnp.bfloat16,
    ...     num_q_heads=12,
    ...     num_kv_heads=12,
    ...     head_dim=64,
    ...     page_size=32,
    ...     max_num_tokens=1024,
    ...     pages_per_seq=128,
    ... )

Note:
    The tuned block sizes are empirically determined through extensive
    benchmarking on various TPU configurations. Default fallback values
    are provided when exact matches are not found in the tuning tables.
"""

import re

import jax
import jax.numpy as jnp


def cdiv(a, b):
    """Compute ceiling division of a by b.

    Args:
        a: Dividend (numerator).
        b: Divisor (denominator). Must be non-zero.

    Returns:
        The smallest integer >= a/b.
    """
    assert b != 0
    return (a + b - 1) // b


def align_to(x, a):
    """Round x up to the nearest multiple of a.

    Args:
        x: Value to align.
        a: Alignment boundary. Must be non-zero.

    Returns:
        The smallest multiple of a that is >= x.
    """
    return cdiv(x, a) * a


def get_dtype_bitwidth(dtype):
    """Return the bit width of a JAX/NumPy dtype.

    Handles both floating-point and integer types by trying finfo first,
    then falling back to iinfo.

    Args:
        dtype: A JAX or NumPy dtype (e.g., jnp.bfloat16, jnp.int8).

    Returns:
        Number of bits per element for the given dtype.
    """
    try:
        return jnp.finfo(dtype).bits
    except Exception:
        return jnp.iinfo(dtype).bits


def get_dtype_packing(dtype):
    """Compute the packing factor for a dtype relative to 32-bit words.

    Determines how many elements of the given dtype fit within a single
    32-bit word. Used for TPU's packed memory layout where sub-32-bit
    types are packed together.

    Args:
        dtype: A JAX or NumPy dtype.

    Returns:
        Number of elements that pack into a 32-bit word (e.g., 1 for
        float32, 2 for bfloat16/float16, 4 for int8).
    """
    bits = get_dtype_bitwidth(dtype)
    return 32 // bits


def next_power_of_2(x: int):
    """Finds the smallest power of 2 >= x using bit manipulation.

    Args:
      x: The input number (should be an integer).

    Returns:
      The smallest integer power of 2 that is >= x.
    """
    assert x > 0
    if x == 1:
        return 1
    return 1 << (x - 1).bit_length()


def get_device_name(num_devices: int | None = None):
    """Detect the TPU device name with normalized variant suffix.

    Normalizes device kind strings from JAX into a canonical form like
    "TPU v5e", "TPU v5p", "TPU v6e", or "TPU v7". Optionally appends
    the device count for multi-chip configurations.

    Args:
        num_devices: Optional device count to append (e.g., 4 yields
            "TPU v5e-4"). Defaults to None (no suffix).

    Returns:
        Normalized TPU device name string.

    Raises:
        RuntimeError: If no TPU devices are found.
        AssertionError: If device kind string is malformed.
    """
    kind = jax.devices()[0].device_kind
    if "TPU" not in kind:
        raise RuntimeError("Expected TPU devices")
    suffix = ""
    if kind.endswith(" lite"):
        kind = kind[: -len(" lite")]
        suffix = "e"
    elif kind.endswith("e"):
        kind = kind[:-1]
        suffix = "e"
    elif kind.endswith("p"):
        kind = kind[:-1]
        suffix = "p"
    elif kind == "TPU7x":
        kind = "TPU v7"
    assert kind[:-1] == "TPU v", kind
    kind += suffix
    if num_devices is not None:
        kind += f"-{num_devices}"
    return kind


def get_tpu_version() -> int:
    """Returns the numeric version of the TPU, or -1 if not on TPU."""
    kind = jax.devices()[0].device_kind
    if "TPU" not in kind:
        return -1
    if kind.endswith(" lite"):
        kind = kind[: -len(" lite")]
    if kind.endswith("p"):
        kind = kind[:-1]
    if kind == "TPU7x":
        return 7
    assert kind[:-1] == "TPU v", kind
    return int(kind[-1])


_HEAD_KEY_RE = re.compile(r"q_head-(\d+)_kv_head-(\d+)_head-(\d+)")
_DTYPE_KEY_RE = re.compile(r"q_(.+?)_kv_(.+)$")

TUNED_KERNEL_NAME = "ragged_page_attention_v3"


def lookup_tuned_block_sizes(device, page_size, dtypes, head_dims, max_model_len):
    """Query the shipped tuned-kernel table for ``(bkv_pages, bq)``.

    The values used to live in a ~4200-line ``TUNED_BLOCK_SIZES`` literal in this
    module. They now live as rows in ``ejkernel/ops/tuned/tuned_kernels.db``,
    which is the same data with an index on it: nothing is parsed at import, the
    schema is shared with every other kernel, and rows are regenerated by sweeps
    rather than hand-edited.

    Key derivation is unchanged -- callers still pass the components
    ``get_lookup_keys``/``get_lookup_keys_h64`` produce.

    Args:
        device: Device name, e.g. ``"TPU v6e"``.
        page_size: Tokens per KV page (already power-of-2 normalized).
        dtypes: ``"q_<dtype>_kv_<dtype>"`` key.
        head_dims: ``"q_head-<n>_kv_head-<n>_head-<n>"`` key.
        max_model_len: Context length (already power-of-2 normalized).

    Returns:
        ``(num_kv_pages_per_block, num_queries_per_block)``, or ``None`` when the
        combination was never measured, so the caller keeps its default.

    Note:
        The lookup is exact-match only. The previous dict indexing fell back to
        the TPU-version default on a miss, and silently substituting a
        neighbouring shape here would be a behaviour change, not a lookup. Dump
        the shipped rows with ``python -m ejkernel.ops.tuned dump``.
    """
    dm = _DTYPE_KEY_RE.match(dtypes)
    hm = _HEAD_KEY_RE.match(head_dims)
    if dm is None or hm is None:
        return None
    try:
        from ejkernel.ops.tuned import dtype_signature, shape_signature, tuned_choice
    except Exception:
        return None
    entry = tuned_choice(
        TUNED_KERNEL_NAME,
        dtypes=dtype_signature(q=dm.group(1), kv=dm.group(2)),
        shape=shape_signature(
            page_size=page_size,
            q_heads=int(hm.group(1)),
            kv_heads=int(hm.group(2)),
            head_dim=int(hm.group(3)),
            max_len=max_model_len,
        ),
        device=device,
        allow_nearest=False,
    )
    if entry is None:
        return None
    cfg = entry.config
    try:
        return int(cfg["num_kv_pages_per_block"]), int(cfg["num_queries_per_block"])
    except (KeyError, TypeError, ValueError):
        return None


def get_tuned_block_sizes_h64(
    q_dtype,
    kv_dtype,
    actual_num_q_heads,
    actual_num_kv_heads,
    head_dim,
    page_size,
    max_num_tokens,
    pages_per_seq,
) -> tuple[int, int]:
    """Search tuned block sizes for head_dim=64 attention configurations.

    Looks up empirically tuned (bkv_pages, bq_size) values from the
    tuned-kernel table for head_dim=64 models. Falls back to
    TPU-version-specific defaults when no exact match is found.

    Args:
        q_dtype: Query tensor dtype (e.g., jnp.bfloat16).
        kv_dtype: KV cache dtype (e.g., jnp.bfloat16, jnp.int8).
        actual_num_q_heads: Number of query attention heads.
        actual_num_kv_heads: Number of KV attention heads.
        head_dim: Head dimension (must be 64).
        page_size: Number of tokens per KV cache page.
        max_num_tokens: Maximum number of tokens in the batch.
        pages_per_seq: Maximum pages allocated per sequence.

    Returns:
        Tuple of (num_kv_pages_per_block, num_queries_per_block),
        clamped to the available pages_per_seq and max_num_tokens.

    Raises:
        NotImplementedError: If TPU version is less than 4.
    """

    tpu_version = get_tpu_version()
    if tpu_version < 4:
        raise NotImplementedError("TPU version must be 4 or higher.")
    match tpu_version:
        case 4:
            bkv_p, bq = (512 // page_size, 32)
        case 7:
            bkv_p, bq = (4096 // page_size, 32)
        case _:
            bkv_p, bq = (2048 // page_size, 32)

    keys = get_lookup_keys_h64(
        page_size,
        q_dtype,
        kv_dtype,
        actual_num_q_heads,
        actual_num_kv_heads,
        head_dim,
        page_size * pages_per_seq,
    )
    device, page_size, dtypes, head_dims, max_model_len = keys

    tuned = lookup_tuned_block_sizes(device, page_size, dtypes, head_dims, max_model_len)
    if tuned is not None:
        bkv_p, bq = tuned

    return (min(pages_per_seq, bkv_p), min(max_num_tokens, bq))


def get_lookup_keys_h64(
    page_size,
    q_dtype,
    kv_dtype,
    num_q_heads,
    num_kv_heads,
    head_dim,
    max_model_len,
):
    """Build hierarchical lookup keys for the head_dim=64 tuning table.

    Constructs the key components used to query the tuned-kernel table.
    Keys are normalized using power-of-2 rounding and dtype-aware
    packing for consistent lookup across similar configurations.

    Args:
        page_size: Number of tokens per KV cache page.
        q_dtype: Query dtype.
        kv_dtype: KV cache dtype.
        num_q_heads: Number of query attention heads.
        num_kv_heads: Number of KV attention heads.
        head_dim: Head dimension (must be 64).
        max_model_len: Maximum model context length in tokens.

    Returns:
        Tuple of (device_name, page_size, dtype_key, head_key, max_len).
    """
    (
        page_size,
        q_dtype_name,
        kv_dtype_name,
        num_q_heads,
        num_kv_heads,
        head_dim,
        max_model_len,
    ) = get_simplified_raw_key_h64(
        page_size,
        q_dtype,
        kv_dtype,
        num_q_heads,
        num_kv_heads,
        head_dim,
        max_model_len,
    )

    return (
        get_device_name(),
        next_power_of_2(page_size),
        f"q_{q_dtype_name}_kv_{kv_dtype_name}",
        f"q_head-{num_q_heads}_kv_head-{num_kv_heads}_head-{head_dim}",
        next_power_of_2(max_model_len),
    )


def get_simplified_raw_key_h64(
    page_size,
    q_dtype,
    kv_dtype,
    actual_num_q_heads,
    actual_num_kv_heads,
    head_dim,
    max_model_len,
):
    """Compute simplified, normalized key components for head_dim=64 lookup.

    Normalizes attention configuration parameters into canonical forms
    for consistent tuning table lookup. Unlike the standard variant,
    this uses single-head KV packing (no x2 interleaving) since
    head_dim=64 concatenates K and V within one head dimension.

    Args:
        page_size: Number of tokens per KV cache page.
        q_dtype: Query dtype.
        kv_dtype: KV cache dtype.
        actual_num_q_heads: Number of query attention heads.
        actual_num_kv_heads: Number of KV attention heads.
        head_dim: Head dimension (must be 64).
        max_model_len: Maximum model context length in tokens.

    Returns:
        Tuple of (page_size, q_dtype_name, kv_dtype_name, num_q_heads,
        num_kv_heads, head_dim, max_model_len) all normalized.
    """
    assert head_dim == 64
    assert actual_num_q_heads % actual_num_kv_heads == 0
    actual_num_q_heads_per_kv_head = actual_num_q_heads // actual_num_kv_heads
    q_packing = get_dtype_packing(q_dtype)
    kv_packing = get_dtype_packing(kv_dtype)
    num_kv_heads = align_to(actual_num_kv_heads, kv_packing)
    num_q_heads_per_kv_head = align_to(actual_num_q_heads_per_kv_head, q_packing)

    return (
        next_power_of_2(page_size),
        jnp.dtype(q_dtype).name,
        jnp.dtype(kv_dtype).name,
        next_power_of_2(num_q_heads_per_kv_head * actual_num_kv_heads),
        next_power_of_2(num_kv_heads),
        head_dim,
        next_power_of_2(max_model_len),
    )


def get_tuned_block_sizes(
    q_dtype,
    kv_dtype,
    actual_num_q_heads,
    actual_num_kv_heads,
    head_dim,
    page_size,
    max_num_tokens,
    pages_per_seq,
) -> tuple[int, int]:
    """Search tuned block sizes for standard attention configurations (head_dim >= 128).

    Looks up empirically tuned (bkv_pages, bq_size) values from the
    TUNED_BLOCK_SIZES table for standard head dimensions (128, 256).
    Falls back to TPU-version-specific defaults when no exact match
    is found in the tuning table.

    Args:
        q_dtype: Query tensor dtype (e.g., jnp.bfloat16).
        kv_dtype: KV cache dtype (e.g., jnp.bfloat16, jnp.int8).
        actual_num_q_heads: Number of query attention heads.
        actual_num_kv_heads: Number of KV attention heads.
        head_dim: Head dimension (typically 128 or 256, already padded).
        page_size: Number of tokens per KV cache page.
        max_num_tokens: Maximum number of tokens in the batch.
        pages_per_seq: Maximum pages allocated per sequence.

    Returns:
        Tuple of (num_kv_pages_per_block, num_queries_per_block),
        clamped to the available pages_per_seq and max_num_tokens.

    Raises:
        NotImplementedError: If TPU version is less than 4.
    """

    tpu_version = get_tpu_version()
    if tpu_version < 4:
        raise NotImplementedError("TPU version must be 4 or higher.")
    match tpu_version:
        case 4:
            bkv_p, bq = (512 // page_size, 32)
        case 7:
            bkv_p, bq = (4096 // page_size, 32)
        case _:
            bkv_p, bq = (2048 // page_size, 32)

    keys = get_lookup_keys(
        page_size,
        q_dtype,
        kv_dtype,
        actual_num_q_heads,
        actual_num_kv_heads,
        head_dim,
        page_size * pages_per_seq,
    )
    device, page_size, dtypes, head_dims, max_model_len = keys

    tuned = lookup_tuned_block_sizes(device, page_size, dtypes, head_dims, max_model_len)
    if tuned is not None:
        bkv_p, bq = tuned
    return (min(pages_per_seq, bkv_p), min(max_num_tokens, bq))


def get_lookup_keys(
    page_size,
    q_dtype,
    kv_dtype,
    num_q_heads,
    num_kv_heads,
    head_dim,
    max_model_len,
):
    """Build hierarchical lookup keys for the standard tuning table.

    Constructs the key components used to query the tuned-kernel table
    for head_dim >= 128 configurations. Keys are normalized using
    power-of-2 rounding and dtype-aware packing.

    Args:
        page_size: Number of tokens per KV cache page.
        q_dtype: Query dtype.
        kv_dtype: KV cache dtype.
        num_q_heads: Number of query attention heads.
        num_kv_heads: Number of KV attention heads.
        head_dim: Head dimension (128 or 256).
        max_model_len: Maximum model context length in tokens.

    Returns:
        Tuple of (device_name, page_size, dtype_key, head_key, max_len).
    """
    (
        page_size,
        q_dtype_name,
        kv_dtype_name,
        num_q_heads,
        num_kv_heads,
        head_dim,
        max_model_len,
    ) = get_simplified_raw_key(
        page_size,
        q_dtype,
        kv_dtype,
        num_q_heads,
        num_kv_heads,
        head_dim,
        max_model_len,
    )

    return (
        get_device_name(),
        next_power_of_2(page_size),
        f"q_{q_dtype_name}_kv_{kv_dtype_name}",
        f"q_head-{num_q_heads}_kv_head-{num_kv_heads}_head-{head_dim}",
        next_power_of_2(max_model_len),
    )


def get_simplified_raw_key(
    page_size,
    q_dtype,
    kv_dtype,
    actual_num_q_heads,
    actual_num_kv_heads,
    head_dim,
    max_model_len,
):
    """Compute simplified, normalized key components for standard lookup.

    Normalizes attention configuration parameters into canonical forms
    for consistent tuning table lookup. Uses x2 interleaved KV head
    packing where keys and values are stored together per head.

    Args:
        page_size: Number of tokens per KV cache page.
        q_dtype: Query dtype.
        kv_dtype: KV cache dtype.
        actual_num_q_heads: Number of query attention heads.
        actual_num_kv_heads: Number of KV attention heads.
        head_dim: Head dimension (128 or 256).
        max_model_len: Maximum model context length in tokens.

    Returns:
        Tuple of (page_size, q_dtype_name, kv_dtype_name, num_q_heads,
        num_kv_heads, head_dim, max_model_len) all normalized.
    """
    assert actual_num_q_heads % actual_num_kv_heads == 0
    actual_num_q_heads_per_kv_head = actual_num_q_heads // actual_num_kv_heads
    q_packing = get_dtype_packing(q_dtype)
    kv_packing = get_dtype_packing(kv_dtype)
    num_kv_heads_x2 = align_to(actual_num_kv_heads * 2, kv_packing)
    num_q_heads_per_kv_head = align_to(actual_num_q_heads_per_kv_head, q_packing)
    assert num_kv_heads_x2 % 2 == 0

    return (
        next_power_of_2(page_size),
        jnp.dtype(q_dtype).name,
        jnp.dtype(kv_dtype).name,
        next_power_of_2(num_q_heads_per_kv_head * actual_num_kv_heads),
        next_power_of_2(num_kv_heads_x2) // 2,
        align_to(head_dim, 128),
        next_power_of_2(max_model_len),
    )
