# Copyright 2026 The EASYDEL Author @erfanzar (Erfan Zare Chavoshi).
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Typed registry for EasyDeL-owned environment flags.

A single catalog of the environment variables EasyDeL reads, each with a type,
default, owning subsystem, and one-line doc. The typed getters
(:func:`get_bool` / :func:`get_int` / :func:`get_float` / :func:`get_str`) read
``os.environ`` **at call time**, so a flag set after import (e.g. by a test) is
honored and stays togglable per run.

All EasyDeL-owned flags use the ``EASYDEL_`` prefix (the eSurge subsystem was
unified onto it — the old ``EASURGE_`` names were removed with no alias). Flags
owned by the foundation libraries keep their own prefixes (``EJKERNEL_``,
``EFORMER_``) and are not registered here; ``EASYDEL_CACHE_COMPILES`` /
``EASYDEL_RECOMPILE_FORCE`` are read by ejkernel's ``callib`` by intentional
cross-package agreement.

:func:`render_markdown` emits a documentation table of every registered flag,
grouped by subsystem, for ``docs/environment_variables.md``.
"""

from __future__ import annotations

import os
import typing as tp
from dataclasses import dataclass

from .helpers import check_bool_flag

__all__ = [
    "FlagSpec",
    "get_bool",
    "get_float",
    "get_int",
    "get_str",
    "registered_flags",
    "render_markdown",
]


@dataclass(frozen=True)
class FlagSpec:
    """Definition of a single EasyDeL environment flag.

    Attributes:
        name: Environment variable name (``EASYDEL_...``).
        kind: One of ``"bool"``, ``"int"``, ``"float"``, ``"str"``.
        default: Value used when the variable is unset (or invalid).
        subsystem: Human-readable owner group used for documentation.
        doc: One-line description of what the flag does.
    """

    name: str
    kind: str
    default: tp.Any
    subsystem: str
    doc: str


_REGISTRY: dict[str, FlagSpec] = {}


def _register(name: str, kind: str, default: tp.Any, subsystem: str, doc: str) -> str:
    """Register a flag spec and return its name (for use as a module constant)."""
    if name in _REGISTRY:
        raise ValueError(f"flag {name!r} is already registered")
    _REGISTRY[name] = FlagSpec(name=name, kind=kind, default=default, subsystem=subsystem, doc=doc)
    return name


def registered_flags() -> tuple[FlagSpec, ...]:
    """Return all registered flag specs (sorted by subsystem then name)."""
    return tuple(sorted(_REGISTRY.values(), key=lambda s: (s.subsystem, s.name)))


def _spec(name: str) -> FlagSpec:
    try:
        return _REGISTRY[name]
    except KeyError as exc:
        raise KeyError(f"{name!r} is not a registered EasyDeL flag (see easydel.utils.flags).") from exc


def get_bool(name: str) -> bool:
    """Read a registered boolean flag from the environment at call time.

    Uses :func:`easydel.utils.helpers.check_bool_flag` truthiness
    (``true``/``yes``/``ok``/``1``/``easy``), falling back to the registered
    default when unset.
    """
    return check_bool_flag(name, bool(_spec(name).default))


def get_int(name: str) -> int:
    """Read a registered integer flag from the environment at call time."""
    default = int(_spec(name).default)
    raw = os.environ.get(name)
    if raw is None or raw == "":
        return default
    try:
        return int(raw)
    except (TypeError, ValueError):
        return default


def get_float(name: str) -> float:
    """Read a registered float flag from the environment at call time."""
    default = float(_spec(name).default)
    raw = os.environ.get(name)
    if raw is None or raw == "":
        return default
    try:
        return float(raw)
    except (TypeError, ValueError):
        return default


def get_str(name: str) -> str | None:
    """Read a registered string flag from the environment at call time.

    Returns the registered default (commonly ``None``) when unset or empty.
    """
    raw = os.environ.get(name)
    if raw is None or raw == "":
        return _spec(name).default
    return raw


def render_markdown() -> str:
    """Render the registered flags as a Markdown document grouped by subsystem."""
    lines = [
        "<!-- generated by easydel.utils.flags.render_markdown - do not edit by hand -->",
        "# EasyDeL-owned environment flags",
        "",
        "Typed, call-time flags registered in `easydel/utils/flags.py`. Booleans use "
        "`check_bool_flag` truthiness (`true`/`yes`/`ok`/`1`/`easy`).",
        "",
    ]
    subsystem = None
    for spec in registered_flags():
        if spec.subsystem != subsystem:
            subsystem = spec.subsystem
            lines += ["", f"## {subsystem}", "", "| Flag | Type | Default | Description |", "| --- | --- | --- | --- |"]
        default = "none" if spec.default is None else f"`{spec.default}`"
        lines.append(f"| `{spec.name}` | {spec.kind} | {default} | {spec.doc} |")
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------- #
# Catalog of EasyDeL-owned eSurge / speculative-decoding flags.
#
# The names below double as importable constants so call sites read
# ``flags.EASYDEL_SPEC_RECURRENT_REPLAY`` instead of a bare string literal.
# --------------------------------------------------------------------------- #

# eSurge engine / scheduler
EASYDEL_MAX_SCHEDULER_ERRORS = _register(
    "EASYDEL_MAX_SCHEDULER_ERRORS", "int", 5, "eSurge engine",
    "Max consecutive scheduler errors before the eSurge engine loop stops.",
)
EASYDEL_HEARTBEAT_WARN_S = _register(
    "EASYDEL_HEARTBEAT_WARN_S", "float", 120.0, "eSurge engine",
    "Seconds without a scheduler heartbeat before a stall warning is logged.",
)
EASYDEL_HEARTBEAT_WARN_INTERVAL_S = _register(
    "EASYDEL_HEARTBEAT_WARN_INTERVAL_S", "float", 30.0, "eSurge engine",
    "Minimum seconds between repeated scheduler-stall warnings.",
)
EASYDEL_TOKENIZER_ENDPOINT = _register(
    "EASYDEL_TOKENIZER_ENDPOINT", "str", None, "eSurge engine",
    "Overrides the tokenizer worker ZeroMQ endpoint.",
)
EASYDEL_DETOKENIZER_ENDPOINT = _register(
    "EASYDEL_DETOKENIZER_ENDPOINT", "str", None, "eSurge engine",
    "Overrides the detokenizer worker ZeroMQ endpoint.",
)
EASYDEL_WORKER_STARTUP_TIMEOUT = _register(
    "EASYDEL_WORKER_STARTUP_TIMEOUT", "float", 120.0, "eSurge engine",
    "Seconds to wait for a tokenizer/detokenizer worker to bind before timing out.",
)

# eSurge runner / execution
EASYDEL_SYNC_INPUTS_FOR_TIMING = _register(
    "EASYDEL_SYNC_INPUTS_FOR_TIMING", "bool", False, "eSurge runner",
    "Sync step inputs for accurate timing (adds a device round-trip).",
)
EASYDEL_ENABLE_DP_LOCAL_PAGE_PATH = _register(
    "EASYDEL_ENABLE_DP_LOCAL_PAGE_PATH", "bool", True, "eSurge runner",
    "Enable the data-parallel local-page attention path when the request count divides evenly.",
)

# eSurge speculative decoding
EASYDEL_SPEC_RECURRENT_REPLAY = _register(
    "EASYDEL_SPEC_RECURRENT_REPLAY", "bool", False, "eSurge spec-decode",
    "Bit-exact greedy under spec-decode via sequential-GDN replay of the accepted prefix (slower; opt-in).",
)
EASYDEL_DISABLE_BATCHED_DRAFT = _register(
    "EASYDEL_DISABLE_BATCHED_DRAFT", "bool", False, "eSurge spec-decode",
    "A/B fallback: force the per-request MTP draft path instead of the batched drafter.",
)
EASYDEL_DISABLE_BATCHED_EMIT = _register(
    "EASYDEL_DISABLE_BATCHED_EMIT", "bool", False, "eSurge spec-decode",
    "A/B fallback: force the per-request MTP emit path instead of the batched emit.",
)
EASYDEL_MTP_PERSIST_KV = _register(
    "EASYDEL_MTP_PERSIST_KV", "bool", False, "eSurge spec-decode",
    "Persist the MTP drafter KV cache across verify windows.",
)
