# Copyright 2025 The EasyDeL Author @erfanzar (Erfan Zare Chavoshi).
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""EasyDeL model modules.

This package provides JAX/Flax implementations of various transformer and
state-space model architectures. Each submodule contains configuration,
base model, and task-specific variants (causal LM, sequence classification,
vision-language, etc.).

Available model families include:
- Decoder-only transformers: LLaMA, Mistral, Qwen, Gemma, Phi, Falcon, etc.
- Mixture-of-experts: DeepSeek, Mixtral, Grok, DBRX, Arctic, etc.
- Vision-language: LLaVA, CLIP, SigLIP, Qwen-VL, GLM-4V, etc.
- State-space: Mamba, Mamba2, RWKV, Falcon Mamba, etc.
- Encoder-only: RoBERTa
- Seq2Seq: Whisper, T5
"""

from . import (
    arctic,
    auto,
    aya_vision,
    clip,
    cohere,
    cohere2,
    dbrx,
    deepseek_v2,
    deepseek_v3,
    exaone,
    exaone4,
    falcon,
    falcon_h1,
    falcon_mamba,
    gemma,
    gemma2,
    gemma3,
    gidd,
    glm,
    glm4,
    glm4_moe,
    glm4v,
    glm4v_moe,
    glm46v,
    gpt2,
    gpt_j,
    gpt_neox,
    gpt_oss,
    grok_1,
    internlm2,
    kimi_linear,
    kimi_vl,
    llama,
    llama4,
    llava,
    mamba,
    mamba2,
    minimax,
    mistral,
    mistral3,
    mixtral,
    mosaic_mpt,
    olmo,
    olmo2,
    olmo3,
    openelm,
    opt,
    phi,
    phi3,
    phimoe,
    pixtral,
    qwen2,
    qwen2_moe,
    qwen2_vl,
    qwen3,
    qwen3_moe,
    qwen3_next,
    qwen3_omni_moe,
    qwen3_vl,
    qwen3_vl_moe,
    roberta,
    rwkv,
    seed_oss,
    siglip,
    smollm3,
    stablelm,
    whisper,
    xerxes,
    xerxes2,
)

__all__ = (
    "arctic",
    "auto",
    "aya_vision",
    "clip",
    "cohere",
    "cohere2",
    "dbrx",
    "deepseek_v2",
    "deepseek_v3",
    "exaone",
    "exaone4",
    "falcon",
    "falcon_h1",
    "falcon_mamba",
    "gemma",
    "gemma2",
    "gemma3",
    "gidd",
    "glm",
    "glm4",
    "glm4_moe",
    "glm4v",
    "glm4v_moe",
    "glm46v",
    "gpt2",
    "gpt_j",
    "gpt_neox",
    "gpt_oss",
    "grok_1",
    "internlm2",
    "kimi_linear",
    "kimi_vl",
    "llama",
    "llama4",
    "llava",
    "mamba",
    "mamba2",
    "minimax",
    "minimax_text_v1",
    "mistral",
    "mistral3",
    "mixtral",
    "mosaic_mpt",
    "olmo",
    "olmo2",
    "olmo3",
    "openelm",
    "opt",
    "phi",
    "phi3",
    "phimoe",
    "pixtral",
    "qwen2",
    "qwen2_moe",
    "qwen2_vl",
    "qwen3",
    "qwen3_moe",
    "qwen3_next",
    "qwen3_omni_moe",
    "qwen3_vl",
    "qwen3_vl_moe",
    "roberta",
    "rwkv",
    "seed_oss",
    "siglip",
    "smollm3",
    "stablelm",
    "whisper",
    "xerxes",
    "xerxes2",
)
