# Copyright 2026 The EASYDEL Author @erfanzar (Erfan Zare Chavoshi).
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Configuration dataclass for the GKD trainer.

Defines :class:`GKDConfig`, the algorithm knobs that ride on top of
:class:`SFTConfig`: the Jensen-Shannon mixing parameter ``beta``, the
on-policy mixing rate ``lmbda``, the temperature, etc.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from easydel.utils import Registry
from easydel.utils.compiling_utils import hash_fn

from ..supervised_fine_tuning_trainer import SFTConfig


@Registry.register("trainer-arguments", "gkd")
@dataclass
class GKDConfig(SFTConfig):
    """Configuration for the :class:`~easydel.trainers.GKDTrainer`.

    GKD (Agarwal et al. 2024) generalises offline knowledge
    distillation by:

    1. Replacing the standard forward KL with the *generalized
       Jensen-Shannon divergence* ``JSD_beta``, which interpolates
       between ``KL(student || teacher)`` (``beta == 0``) and
       ``KL(teacher || student)`` (``beta == 1``) through the
       ``beta``-mixed midpoint distribution.
    2. Optionally training on student-generated on-policy rollouts at
       a per-batch probability ``lmbda``, mitigating the
       distribution-shift problem of offline distillation.
    3. Optionally pre-generating the batch with the teacher
       (sequence-level KD, ``seq_kd=True``) to focus the loss on the
       teacher's preferred trajectories.

    Extends :class:`~easydel.trainers.SFTConfig` so all SFT-style
    tokenisation, packing, and chat-template knobs are inherited
    verbatim.

    Attributes:
        trainer_prefix: Default prefix used for checkpoints/logs
            (``"GKD"``).
        temperature: Softmax temperature applied both during on-policy
            generation and inside the JSD loss. Larger values produce
            softer targets. Default ``0.9``.
        lmbda: Probability of replacing the supervised batch with
            on-policy student samples. ``None`` (or ``<= 0``) disables
            on-policy sampling. Validated in ``[0, 1]``. Default ``0.5``.
        beta: Mixing weight inside the generalised JSD loss. ``0.0``
            recovers ``KL(student || teacher)``; ``1.0`` recovers
            ``KL(teacher || student)``. Validated in ``[0, 1]``.
            Default ``0.5``.
        max_new_tokens: Maximum number of tokens generated per prompt
            during on-policy rollouts. Default ``128``.
        disable_dropout: When ``True``, dropout is disabled on both
            student and teacher for deterministic distillation
            targets.
        seq_kd: When ``True``, the batch is always regenerated by the
            teacher before any student-side processing
            (sequence-level KD). Stacks with ``lmbda`` for hybrid
            schedules.
    """

    trainer_prefix: str | None = field(
        default="GKD",
        metadata={"help": "Default prefix used for checkpoints and logs."},
    )
    temperature: float = field(
        default=0.9,
        metadata={"help": "Generation temperature as well as the softmax temperature used when computing the GKD loss."},
    )
    lmbda: float | None = field(
        default=0.5,
        metadata={
            "help": "Probability of performing on-policy student generation for a batch. "
            "Set to `None` to disable on-policy sampling; `0` is accepted for backward compatibility."
        },
    )
    beta: float = field(
        default=0.5,
        metadata={
            "help": "Interpolation factor in the generalized Jensen-Shannon divergence. "
            "0.0 reduces to KL(student‖teacher) while 1.0 becomes KL(teacher‖student)."
        },
    )
    max_new_tokens: int = field(
        default=128,
        metadata={"help": "Maximum number of tokens to generate during on-policy rollouts."},
    )
    disable_dropout: bool = field(
        default=True,
        metadata={"help": "Disable dropout in both student and teacher models for more stable distillation."},
    )
    seq_kd: bool = field(
        default=False,
        metadata={"help": "Enable sequence-level KD by always regenerating the batch with the teacher before training."},
    )

    __hash__ = hash_fn

    def __post_init__(
        self,
        max_sequence_length: int | None,
        quantization_block: int | None,
    ):
        """Forward to the SFT base class then validate GKD-specific knobs.

        Args:
            max_sequence_length: Legacy alias for ``max_length``.
            quantization_block: Legacy alias for the quantization group
                size.

        Raises:
            ValueError: If ``lmbda`` is outside ``[0, 1]``, ``beta`` is
                outside ``[0, 1]``, or ``max_new_tokens`` is non-positive.
        """
        super().__post_init__(
            max_sequence_length=max_sequence_length,
            quantization_block=quantization_block,
        )
        if self.lmbda is not None:
            normalized_lmbda = float(self.lmbda)
            self.lmbda = normalized_lmbda if normalized_lmbda > 0.0 else None
            if self.lmbda is not None and not 0.0 <= self.lmbda <= 1.0:
                raise ValueError("`lmbda` must be within [0, 1].")
        if not 0.0 <= self.beta <= 1.0:
            raise ValueError("`beta` must be within [0, 1].")
        if self.max_new_tokens <= 0:
            raise ValueError("`max_new_tokens` must be strictly positive.")
